name: Generate Journal
on:
  push:
    branches:
      - '**'
jobs:
  run-script-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Execute Shell Script
        run: 
          chmod +x ./journals/genjournal.sh
          ./journals/genjournal.sh
